version: '3'

services:
  mydb:                                 
    image: postgres:12.6                
    volumes:
      - postgresdb:/var/lib/postgresql  
    ports:                               
      - "5432:5432"                     
    environment:                        
      POSTGRES_USER: admin              
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: testdb

volumes:                                
  postgresdb:
    driver: local